30 dashboard frontend
DylanHalstead/ClassConnect pull request #40
Opened 2024-02-27 18:56 UTC by Sm3ggl3s

Closes #30 

# Problem
We needed a page users can quickly view a summary of bookings as well as quickly create a booking.

# Solution
Created the frontend of a dashboard page that the users can easily navigate. 

<img width="1429" alt="Screenshot 2024-02-27 at 13 23 13" src="https://github.com/DylanHalstead/ClassConnect/assets/36448138/e01bee5f-f9f4-4913-8291-a2cc168ab2d5">

Planning next to add the backend functionality as well as validations within the booking form.

2024-02-27 19:47 UTC, DylanHalstead requested changes
Remove `package-lock 2.json`

2024-02-27 19:47 UTC, DylanHalstead commented on src/lib/components/dashboard/BookingForm.svelte
> +	let selectedClass: any;
Should be the same type as `class`

2024-02-27 19:48 UTC, DylanHalstead commented on src/lib/components/dashboard/BookingForm.svelte
> +	let selectedTA: any;
Same as above

2024-02-27 19:49 UTC, DylanHalstead commented on src/lib/components/dashboard/BookingForm.svelte
> +<form action="" class="form-control w-80">
May want to put this into a component

2024-02-27 19:51 UTC, DylanHalstead commented on src/routes/dashboard/+page.svelte
> +	const weekdays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
Can be found from the `WeekDays` type. `Object.values(WeekDay)` I believe

2024-02-27 19:56 UTC, DylanHalstead commented on src/lib/components/dashboard/BookingForm.svelte
> +<form action="" class="form-control w-80">
I see. So like this form itself should be a component, then the rest should just be on the `+page.svelte` because the content is specific to the pag

2024-02-27 21:51 UTC, DylanHalstead commented
If in Japan while these changes are made, ping me and I'll remove my changes hold. Will trust Jaden to review

2024-03-17 22:28 UTC, Sm3ggl3s reviewed
Removed the second package-lock

2024-03-17 22:31 UTC, Sm3ggl3s commented
I believe I have fixed the form component as well as the other changes. Double check and get back to me.

2024-03-18 17:22 UTC, DylanHalstead commented on src/routes/dashboard/+page.svelte
> +	const weekdays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
Still this ^

2024-03-18 17:24 UTC, DylanHalstead approved these changes

2024-03-18 18:53 UTC, merged