46 login button landing page
DylanHalstead/ClassConnect pull request #50
Opened 2024-03-26 15:20 UTC by Sm3ggl3s

closes #46 

# Problem
User has no way to login from landing page without manually entering the path within the url

# Solution
Added login button as well as sign up button to landing page that redirects user to dashboard once logged in.

![Screenshot 2024-03-26 at 11 11 16](https://github.com/DylanHalstead/ClassConnect/assets/36448138/6b45051c-688e-47ad-a69c-f2c0f9d81f65)

2024-03-26 23:32 UTC, DylanHalstead requested changes
Minor change once fixed lgtm

2024-03-26 23:32 UTC, DylanHalstead commented on src/routes/+layout.server.ts
> +export const load: LayoutServerLoad = loadFlash(async ({ locals, cookies, fetch, url }) => {
Lots of things being deleted here that we won. db should be undefined, there should still be the cookies.set stuff. Basically what was deleted add back and set it undefined

2024-03-30 14:49 UTC, Sm3ggl3s commented on src/routes/+layout.server.ts
> +export const load: LayoutServerLoad = loadFlash(async ({ locals, cookies, fetch, url }) => {
I believe I fixed it. Can you just go in and check I did it correctly.

2024-04-02 19:08 UTC, DylanHalstead approved these changes
:kiss:

2024-04-02 19:11 UTC, merged